export const LOOKS_REQUEST = 'LOOKS_REQUEST';
export const LOOKS_SUCCESS = 'LOOKS_SUCCESS';
export const LOOKS_FAILURE = 'LOOKS_FAILURE';

export const PICKS_REQUEST = 'PICKS_REQUEST';
export const PICKS_SUCCESS = 'PICKS_SUCCESS';
export const PICKS_FAILURE = 'PICKS_FAILURE';

export const CATEGORIES_REQUEST = 'CATEGORIES_REQUEST';
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';
export const CATEGORIES_FAILURE = 'CATEGORIES_FAILURE';

export const BOUTIQUES_REQUEST = 'BOUTIQUES_REQUEST';
export const BOUTIQUES_SUCCESS = 'BOUTIQUES_SUCCESS';
export const BOUTIQUES_FAILURE = 'BOUTIQUES_FAILURE';

export const INSTA_PROFILE_REQUEST = 'INSTA_PROFILE_REQUEST';
export const INSTA_PROFILE_SUCCESS = 'INSTA_PROFILE_SUCCESS';
export const INSTA_PROFILE_FAILURE = 'INSTA_PROFILE_FAILURE';
